services:
  mongodb:
    image: mongo
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/ # Mounts init.js

  backend:
    build: .
    container_name: cadastro-usuarios-backend 
    restart: always
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: "mongodb://my-mongo:27030/cadastro-usuarios"

volumes:
  mongodb_data:
